version: "3"
services:
  bot:
    image: joagonzalez/bot-vulnerability:1.0.5
    build: ./
    # deploy: 
    #   placement: 
    #     constraints: 
    #       - node.platform.os == linux 
    restart: always
    networks:
      - bot_network

networks:
  bot_network:
