version: "3"
services:
  bot:
    image: bot-vulnerability:1.0.2
    build: ./
    # deploy: 
    #   placement: 
    #     constraints: 
    #       - node.platform.os == linux
    restart: always
    networks:
      - bot_network

networks:
  bot_network:
